# Generated by Django 4.1.1 on 2022-10-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_remove_artist_genre_artist_profile_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
