# Generated by Django 4.1.1 on 2022-10-04 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_remove_album_genre_album_cost_and_more'),
        ('artists', '0003_alter_artist_options_alter_artist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='albums.album'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='profile_link',
            field=models.URLField(blank=True, default='https://www.Example.com', max_length=50),
        ),
    ]
