# Generated by Django 4.1.1 on 2022-10-06 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_remove_album_genre_album_cost_and_more'),
        ('artists', '0008_artistalbum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistalbum',
            name='album',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='albums.album'),
        ),
    ]
