# Generated by Django 4.1.1 on 2022-10-03 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artist',
            new_name='Album',
        ),
    ]
