# Generated by Django 4.1.1 on 2022-10-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_album_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='approved',
            field=models.BooleanField(default=False, help_text='Check this box if you want to approve this album.'),
        ),
    ]
