# Generated by Django 4.1.1 on 2022-10-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0006_remove_album_creation_datetime_album_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(default='Album Name', max_length=50, unique=True),
        ),
    ]
