# Generated by Django 4.1.1 on 2022-11-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0008_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_audio',
            field=models.FileField(upload_to='audio/'),
        ),
    ]
